version: '3.8'

services:
  # --- DATABASE ---
  postgres-database:
    image: postgres:15
    container_name: postgres-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ecommerce-net

  # --- USER SERVICE ---
  user-service:
    build:
      context: services/user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8081:8080"
      - "5005:5005"
    environment:
      - DB_HOST=postgres-db
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    depends_on:
      postgres-database:
        condition: service_healthy
    networks:
      - ecommerce-net

  # --- ORDER SERVICE ---
  order-service:
    build:
      context: services/order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8082:8080"
    environment:
      - DB_HOST=postgres-db
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
    depends_on:
      postgres-database:
        condition: service_healthy
    networks:
      - ecommerce-net

  product-service:
    build:
      context: product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8083:8080" # Host 8083 -> container 8083
    environment:
      - DB_HOST=postres-db
      - DB_NAME=${POSTGRES_DB}
      - DB-USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSOWRD}
    depends_on:
      postgres-database:
        condition: service_healthy
    networks:
      - ecommerce-net
volumes:
  postgres-data:
  kafka_data:

networks:
  ecommerce-net:
    driver: bridge
