apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: Mose@198
  POSTGRES_DB: ecommerce_db
  JWT_SECRET_KEY: VGhpcyBpcyByb290LCBNb3NlIFphY2hhcnk=
  DOCKER_USERNAME: mosezac
  DOCKER_PASSWORD: Mose@12055
