name: CI/CD Pipeline

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    env:
      DOCKER_USER: mosezac
      VERSION: v1.0.0

    steps:
      # Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Login to docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push user-service
      - name: Build $ Push user-service
        run:
          cd services/user-service
          mvn -B package --file pom.xml
          docker build -t $DOCKER_USER/user-service:latest
          docker tag @DOCKER_USER/user-service:latest $DOCKER_USER/user-service:${VERSION}
          docker push $DOCKER_USER/user-service:latest
          docker push $DOCKER_USER/user-service:${VERSION}

        # Build and push order-service
      - name: Build $ Push user-service
        run:
          cd services/user-service
          mvn -B package --file pom.xml
          docker build -t $DOCKER_USER/order-service:latest
          docker tag @DOCKER_USER/order-service:latest $DOCKER_USER/order-service:${VERSION}
          docker push $DOCKER_USER/order-service:latest
          docker push $DOCKER_USER/order-service:${VERSION}
