name: CI/CD Pipeline

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

jobs:
  build-and-push:
    runs-on: self-hosted
    env:
      DOCKER_USER: mosezac
      VERSION: v1.0.0

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # --- BUILD USER SERVICE ---
      - name: Build & Push user-service
        run: | 
          cd services/user-service
          mvn -B package --file pom.xml -DskipTests
          docker build -t $DOCKER_USER/user-service:latest . 
          docker tag $DOCKER_USER/user-service:latest $DOCKER_USER/user-service:$VERSION 
          docker push $DOCKER_USER/user-service:latest
          docker push $DOCKER_USER/user-service:$VERSION

      # --- BUILD ORDER SERVICE ---
      - name: Build & Push order-service
        run: |  
          cd services/order-service 
          mvn -B package --file pom.xml -DskipTests
          docker build -t $DOCKER_USER/order-service:latest .
          docker tag $DOCKER_USER/order-service:latest $DOCKER_USER/order-service:$VERSION
          docker push $DOCKER_USER/order-service:latest
          docker push $DOCKER_USER/order-service:$VERSION

      # --- BUILD PRODUCT SERVICE
      - name: Build & Push product-service
        run: |
          cd product-service
          mvn -B package --file pom.xml -DskipTests
          docker build -t $DOCKER_USER/product-service:latest .
          docker push $DOCKER_USER/product-service:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: self-hosted
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to cluster
        run: |
          kubectl apply -f K8s/namespace.yaml || true
          kubectl apply -f K8s/secrets.yaml
          kubectl apply -f K8s/postgres/postgres.yaml
          kubectl apply -f K8s/user-service/service.yaml
          kubectl apply -f K8s/user-service/deployment.yaml
          
          kubectl apply -f K8s/order-service/service.yaml
          kubectl apply -f K8s/order-service/deployment.yaml
          
          kubectl apply -f K8s/product-service/service.yaml
          kubectl apply -f K8s/product-service/deployment.yaml
          

      - name: Restart Deployments
        run: |
          kubectl rollout restart deployment order-service -n ecommerce
          kubectl rollout restart deployment user-service -n ecommerce 
          kubectl rollout restart deployment product-service -n ecommerce